'use strict';
var React = require('react');

var PrivacyPolicy = React.createClass({
  render: function () {
    return (
      <section id="PrivacyPolicy" className="default-page-section">
        <div className="container rich-text narrow">
          <h2 className="h1">CompStak Privacy Policy</h2>
          <p className="h6">Effective Date: December 8, 2011</p>
          <h3>Introduction</h3>
          <p>This policy covers how CompStak® (“CompStak,” “We,” or “Us”) treats Personally Identifiable Information (“PII”) and other information that CompStak collects in connection with our services, whether you are using our services as either a visitor to our website (“Visitor”) or as a user who has completed our registration process (“Members,” Visitors and Members collectively referred to as “Users”). CompStak considers PII to be information that can be traced directly back to and identifies an individual, such as name, address, email address, and/or phone number. We do not consider PII to include information that has been anonymized so that it does not allow a third party to easily identify a specific individual. This policy does not apply to our collection and use of data about commercial properties contained in our Database, which is covered in our Fair Information Statement, available <a href="#FairInformation">here</a>.</p>
          <p>Please read this policy carefully and review it often because it may change. By using this website and accepting the <a href="#TermsOfUse">Terms of Use</a> you agree to this Privacy Policy. IF YOU DO NOT AGREE TO THIS <b>PRIVACY POLICY</b>, YOU MAY NOT USE THE WEBSITE OR SERVICES.</p>
          <p>This Privacy Policy is incorporated into, and made a part of, CompStak’s <a href="#TermsOfUse">Terms of Use</a>, and capitalized terms used and not defined in this policy have the meaning given to them in the Terms of Use.</p>
          <h3>1. Scope of Privacy Policy</h3>
          <p>This Privacy Policy applies to PII and other information collected by CompStak through your use of CompStak or CompStak’s services and does not apply to any other information collected by CompStak through other means. When you navigate away from our website to websites controlled by third parties, you leave the CompStak website, at which point our Privacy Policy no longer applies. We do not provide a notice warning to Users when they are leaving our website.</p>
          <h3>2. The Information We Collect</h3>
          <p>CompStak’s services include the collection, aggregation, and organization of information about commercial properties, such as building information (including, but not limited to, building pictures), completed lease deal information (including, but not limited to, rental rates, leased squared footage, tenant names and real estate broker and salesperson names), and related property, tenant and market information. Members can provide such information for inclusion in our Database. By visiting our website or becoming a Member, you are authorizing us to gather, parse, and retain data and information that you provide to us as necessary to deliver and support our services.</p>
          <p><span className="underlined">PII Collection</span>. CompStak collects PII when you register. We may also collect PII from you in other ways, such as contacts with our customer-support team.</p>
          <p><span className="underlined">Non-PII Collection</span>. Whenever you visit CompStak, we also receive and record information on our server logs from your browser, including your IP address, CompStak cookie information, and the pages you request. We relate this information to the PII you provide. CompStak uses this information to provide our services, to improve our products and services, to contact you, to conduct research, and to develop and maintain anonymous or aggregated data and analytics.</p>
          <p><span className="underlined">Member Screen Names</span>. During registration, Members must create a unique screen name that may be publicly attributed (tied) to their use of our system and may be both displayed in our system or shared in public communications. Screen names are the key to keeping our Members anonymous when they are contributing information about commercial properties. Members should be careful not to include PII in their screen name.</p>
          <p><span className="underlined">Member Passwords</span>. During registration, Members must select a password. Passwords are used to secure Member information and the integrity of the system. We only store a one-way encryption of Member passwords which means passwords cannot be unencrypted by us. Our login page provides a way for Members to obtain access to the system in case they lose or forget their password.</p>
          <p><span className="underlined">System Use Information</span>. We use screen names to compile and process historical and statistical information about how and when our Users use the system. Historical and statistical information includes information about selected actions that our Members take while on the system. We may also aggregate and store historical and statistical information for Members or Visitors. System use information is collected, surveyed, evaluated and scored by the system to assess the quality of data. Member actions are effectively confirmed or challenged by the later actions of other Members. We use this evaluation process to maintain our collaborative, self-correcting system and to promote the development of the most accurate, complete and up-to-date data possible. Members are objectively rated by the system based upon their actions.</p>
          <p>Our system uses points as an incentive and a point balance will be maintained for each Member based upon system use information. We may also use this information to add, adjust or discontinue certain services or functionality and to enforce our policies and procedures. Compiled system use information, Member ratings, point balances and information on data submitted may be displayed online shared along with screen names both online and in other public communications.</p>
          <h3>3. How We Use Your Personal Information</h3>
          <p><span className="underlined">Our use of PII</span>. We use PII for internal and service-related purposes only and we may use vendors and suppliers to allow us to offer CompStak. CompStak does not rent, sell, or share PII about you with other people or non-affiliated companies for marketing purposes. While we do not rent, share, or sell PII to advertisers, we may allow access to other CompStak data to enable the delivery of marketing and offers that will be of the greatest utility, relevance, value, and interest to you.</p>
          <p><span className="underlined">Payment Information</span>. To open a subscription account, Members must enter valid PayPal and/or other payment information needed to process their subscription payments. We use this information for identification and verification purposes and to process payments. We may also use this information to contact Members about payment processing. When Members provide payment information, it is protected using secure socket layer technology (SSL). We do not share credit card or payment information with third parties other than to process payments.</p>
          <p><span className="underlined">Anonymous use and sharing</span>. We may share with third parties anonymized information in the performance of marketing services, including evaluating market trends and/or under a joint marketing agreement to provide services that will be of particular interest and relevance to you. Such information will not include PII. In addition, Members may have access to their information through the 'My Account' area of our system.</p>
          <p><span className="underlined">Communicating with our Members</span>. We will typically communicate with our Members using their registered email address. If we cannot reach our Members by email, we may use other contact information such as their address, telephone number, Twitter ID, Instant Messenger ID, Facebook ID and/or LinkedIn ID. We will communicate with Members in accordance with their preferences and in response to inquiries, to provide requested services and to manage their accounts. We will send Members mandatory service-related announcements and notifications by email when necessary. Members cannot opt-out of these communications, which are not promotional in nature. If Members do not wish to receive them, they have the option of canceling their account. We may broadcast or otherwise distribute important messages to all Users or send individual messages to specific Users where we have appropriate contact information to do so. We also may send information to Members by email about our services, including special alerts, offers, awards, surveys, contests, promotions and updates. Members will be given the option not to receive these types of communications.</p>
          <p><span className="underlined">Surveys and Contests</span>. We may provide Users the opportunity to participate in contests or surveys from time to time. Participation in contests or surveys is completely voluntary. If Users choose to participate, we may request certain additional PII. We may use this information to monitor system traffic, supplement, amend and personalize our system, direct advertisements, communicate with participants, develop our products and services, or conduct market research. We will use email addresses to distribute and collect surveys, notify contest winners and award prizes.</p>
          <p><span className="underlined">Legal sharing for protection of us, you, and others</span>. We may disclose PII to third parties who are assisting us in protecting against or preventing actual or potential fraud, unauthorized transactions, claims or other liabilities, or to investigate potential fraudulent or questionable activities. We may disclose PII in response to legal process, such as in response to a court order or a subpoena. We may disclose PII in response to a law enforcement agency's request, or where we believe it is necessary to investigate, prevent, or take action regarding illegal activities or suspected fraud, violations of our Terms of Use, or as we believe may be otherwise required by law. We may also disclose PII to protect our rights or interests or the rights or interests of others.</p>
          <p><span className="underlined">Merger or sale</span>. If all or substantially all of CompStak or its assets are sold or transferred, PII and other information we have collected may be treated as an asset and transferred in accordance with this Policy.</p>
          <p><span className="underlined">Cookies and related technologies</span>. CompStak uses "cookies." Cookies are small lines of text/data that are written onto a User’s computer by a website to store that User’s preferences. Most browsers allow you to manage cookies including blocking and deleting them. If you block or delete our cookies, CompStak may not work as well or at all for you.</p>
          <p><span className="underlined">Clear gifs (Web beacons)</span>. We use a software technology called clear gifs (a.k.a. web beacons), that help us better manage content on our site by informing us what content is effective. Clear gifs are tiny graphics with a unique identifier, similar in function to cookies, and are used to track the online movements of web users. In contrast to cookies, which are stored on a User's computer hard drive, clear gifs are embedded invisibly on web pages. We tie the information gathered by clear gifs to personally identifiable information Users submit while they are on the system. We use clear gifs in our HTML-based emails to let us know which emails have been opened by recipients. This allows us to gauge the effectiveness of certain communications and the effectiveness of our marketing campaigns.</p>
          <h3>4. How We Secure Your Personal Information</h3>
          <p>CompStak limits access to your PII. We have put in place physical, electronic, and managerial procedures in an effort to safeguard and help prevent unauthorized access, maintain data security, and use correctly the PII we collect from you.</p>
          <p>No data transmissions through the Internet or mobile devices, or even the physical transfer of information, can be guaranteed to be completely secure. We cannot eliminate fully all security risks associated with personal information and technical mistakes are possible. We do not ensure or warrant the security of any data or information you transmit to us and you do so at your own risk.</p>
          <p>If CompStak learns of a security systems breach, then we may attempt to notify you electronically. You agree that we may communicate with you electronically regarding security, privacy, and administrative issues. We may post a notice on our website if a security breach occurs. If this happens, you will need a web browser enabling you to view and access CompStak. We may also send an email to you at the email address you have provided to us. Depending on where you live, you may have a legal right to receive notice of a security breach in writing. To receive free written notice of a security breach (or to withdraw your consent from receiving electronic notice), you should notify us at: CompStak, Inc., Attn: Legal Department, 36 Cooper Square, Sixth Floor, New York, NY 10003.</p>
          <h3>5. Children and International Visitors</h3>
          <p>CompStak is hosted in and intended for use in the United States by adult U.S. residents. Children under the age of 18 are not permitted to use our system. We do not knowingly collect information from or about children.</p>
          <p>If you are visiting from the European Union or other regions with laws governing data collection and use, please note that you are agreeing to the transfer of your personal information to the United States to CompStak. By providing your PII you consent to any transfer and processing in accordance with this Policy.</p>
          <h3>6. How To Contact Us</h3>
          <p>If you have questions or suggestions, please email CompStak at support@compstak.com or call (646) 926-6707. Written communication should be sent to CompStak, Inc., 36 Cooper Square, Sixth Floor, New York, NY 10003.</p>
          <h3>7. To Review Or Correct Your Personal Information</h3>
          <p>Upon request, we will provide an individual with access to PII that we have collected about them (provided that they have given proof of identity). This information can be requested by sending us an email through the email link provided above or writing to us at the above address. This information can be corrected by sending us an email through the email link provided above or writing to us at the above address.</p>
          <h3>8. How We May Update Our Privacy Policy</h3>
          <p>From time to time, we may use PII for new, unanticipated uses not previously disclosed in our Privacy Policy. If our information practices change, we will immediately post any adjustments to our Policy on this website. The revised version usually will be effective at the time we post it; however, if the revised version includes a change that would be materially less restrictive on our use of your PII, we will provide you with 30 days’ prior notice by posting notice of the change on the "Policy Updates" page of our website. If you are concerned about how your information is used, bookmark this page and check back periodically.</p>
        </div>
      </section>
    )
  }
});

module.exports = PrivacyPolicy;