'use strict';
var React = require('react');
var Router = require('react-router');
var HomePageRouterMixin = require('../mixins/HomePageRouter.jsx');
var Icons = require('../components/Icons.jsx');
var Link = Router.Link;

var TermsOfUse = React.createClass({
  render: function () {
    return (
      <section id="TermsOfUse" className="default-page-section">
        <div className="container rich-text narrow">
          <h2 className="h1">CompStak Terms of Use</h2>
          <p className="h6">Effective Date: June 19, 2014</p>
          <h3>1. Introduction</h3>
          <p>Please carefully review these Terms of Use (“<b>TOU</b>” or “<b>Agreement</b>”), for CompStak, Inc. (“<b>CompStak</b>”, “<b>We</b>”, or “<b>Us</b>”) as they contain important information regarding your legal rights, remedies, and obligations. These TOU apply if you visit, view, use, or access (collectively, “<b>access</b>”) CompStak’s websites made available on CompStak.com (the “<b>Website</b>”), and/or (hereinafter, “<b>or</b>”) if, through any Internet-enabled mechanism (including, but not limited to a crawler or bot), you access data, information, products, services, or applications (collectively, with the Website, the “<b>Services</b>”) made available by or from CompStak.</p>
          <h3>2. Legally Binding Agreement</h3>
          <p>By accessing the Services, you represent and warrant that you have read and understood, and agree to be bound by these TOU and that you acknowledge the adequacy of consideration for this Agreement. Please review this document carefully as it is a legally binding document between you and CompStak. <b>If you do not agree to these TOU, you are prohibited from accessing, and must immediately discontinue your access of the Services. Please exit and discontinue all access immediately.</b></p>
          <h3>3. Eligibility</h3>
          <p>The Services are not targeted to, and should not be used by, persons under the age of 18. BY ACCESSING THE SERVICES, YOU REPRESENT AND WARRANT THAT YOU ARE AT LEAST 18 YEARS OLD, ARE LEGALLY QUALIFIED TO ENTER INTO AND FORM CONTRACTS UNDER APPLICABLE LAW, and are not barred from accessing the Services under the laws of any applicable jurisdiction.</p>
          <p>If you are using the Services on behalf of a company, entity, or organization (each a “<b>Subscribing Entity</b>”), then you represent and warrant that you: (i) are an authorized representative of that Subscribing Entity with the authority to bind such entity to the TOU and (ii) agree to be bound by the TOU individually and on behalf of such Subscribing Entity. You further represent and warrant that the Subscribing Entity is not a CompStak Competitor, nor are you or your Subscribing Entity using the Services for or on behalf of a CompStak Competitor, as defined in Section 8(B)(ix).</p>
          <h3>4. Privacy Policy; Changes to Agreement</h3>
          <ol className="abc">
            <li><p><span className="underlined">Privacy Policy</span>. By accessing the Services, you consent to the collection and use of certain information about you, as specified in the Services’ Privacy Policy (the “<b>Privacy Policy</b>”), incorporated hereto and available <a href="#PrivacyPolicy">here</a>. CompStak encourages users of the Services to frequently check the Privacy Policy for changes. By accessing the Services, you represent and warrant that you have read and understood, and agree to be bound by, the Privacy Policy. IF YOU DO NOT UNDERSTAND OR DO NOT AGREE TO BE BOUND BY THE PRIVACY POLICY, YOU MUST IMMEDIATELY EXIT AND DISCONTINUE ALL ACCESS TO THE SERVICES.</p></li>
            <li><p><span className="underlined">Changes</span>. COMPSTAK RESERVES THE RIGHT TO CHANGE THIS AGREEMENT AND/OR THE PRIVACY POLICY AT ANY TIME. Notice of any such change will be given by the posting of a new version or a change notice on the Services; provided, however, that CompStak will use commercially reasonable efforts to notify you of any material changes to these TOU at least 30 days in advance of the effective date of such material change. Changed TOU will be indicated by the “effective date” at the top of this Agreement. If you do not agree to such changes, please exit and discontinue all access to the Services immediately. It is your responsibility to review this Agreement and the Privacy Policy periodically. If at any time you find any TOU or the Privacy Policy unacceptable, you must immediately leave, and refrain from using, the Services.</p></li>
          </ol>
          <h3>5. Member Registration, User Name, and Points</h3>
          <ol className="abc">
            <li><p><span className="underlined">Member Registration</span>. By accessing the Services, you are not automatically a CompStak <b>Member</b>; you are a “Visitor.” In order to become a CompStak member (“Member”), you are required to complete a registration process. You certify, represent and warrant that the information you provide therein is true, accurate, complete, current, and that it belongs to you. You shall keep your information complete and up-to-date at all times. Failure to maintain your registration information may cause your access to the Services to be interrupted, suspended, or terminated. You are responsible for monitoring your account, changing your password periodically and notifying CompStak immediately of any unauthorized use or breach of security of your password.</p></li>
            <li><p><span className="underlined">Members and Contacts</span>. Your Member registration information and information you provide regarding commercial properties is automatically entered into CompStak’s proprietary database (the “<b>Database</b>”), which contains, among other things, building information, completed lease deal information (including, but not limited to rental rates, leased squared footage, tenant name and real estate broker and salesperson name), and related property, tenant and market information. Please note: as a Member, you may contribute to and access the Database; however, CompStak retains all proprietary and intellectual property rights to the Database, and you do not retain any ownership rights in the Database as a result of any information you provide. Likewise, information contributed to the Database may be shared with other Members and with third parties, in CompStak’s discretion. To learn more about our Database, please see Section 10.</p></li>
            <li><p><span className="underlined">User Name</span>. In order to access certain Services as a Member, you must log on with a unique user name or email address.</p></li>
            <li><p><span className="underlined">Points</span>. The Services allow you to earn points or credits (“<b>Points</b>”) by performing certain actions. Points are not real money, do not have monetary value, and may never be redeemed for “real world” money, or other items of monetary value from outside of the Services without our written permission. While we may use terms like “buy”, “earn”, “ spend” or “sell” in reference to Points, we do so only for convenience and such terms in no way indicate that Points have monetary value or are real money. You acknowledge that Points are not real currency and are not redeemable for any sum of money from us at any time. We make no guarantee as to the nature, quality or value of the features of the Services.</p>
              <ol className="roman">
                <li><p><span className="underlined">License</span>. Points obtained via the Services are provided to you under a limited, personal, revocable, non-transferable (except as specifically provided below), non-sublicensable license to use within the Services. Points may not be transferred (except as specifically provided below) or resold in any manner, including, without limitation, by means of any direct sale or auction service. You have no property interest, right or title in or to any such Points appearing or originating in the Services, or any other attributes associated with use of the Services.</p></li>
                <li><p><span className="underlined">Limitation of Liability</span>. We have no liability for hacking or loss of your Points; provided that we will use commercially reasonable efforts to restore Points in the event of any hacking or loss. We have no obligation to, and will not, reimburse you for any Points or any goods or services obtained via Points that are forfeited due to your violation of the TOU. We reserve the right, without prior notification, to limit the quantity of Points and/or to refuse to provide you with any Points. Price, exchangeability, and availability of Points are determined by us in our sole discretion and are subject to change without notice. You agree that we have the absolute right to manage, distribute, regulate, control, modify, cancel, restrict, terminate and/or eliminate Points as we see fit in our sole discretion, and that we will have no liability for exercising such right. You agree that under no circumstances are we liable to you for any damages or claims that may arise from the loss or use of your Points regardless of the circumstances. You absolve us of any responsibility to maintain or update your Points balance. However, if there is a loss of Points in your account due to technical or operational problems with the Services, we may replenish the lost Points once the loss has been verified. Without limiting any of the foregoing, our maximum liability or responsibility to you is to replenish the Points lost.</p></li>
                <li><p><span className="underlined">Redemption</span>. You may redeem Points for CompStak Data or as otherwise set forth on the Services. We will, in our sole discretion, determine and communicate the availability and exchange rate for any Points, which may be modified at any time. All redemptions are subject to the TOU and all limitations and requirements stated via the Services. All redemptions of Points are final. Once your Points have been redeemed, they will be subtracted from your Point balance and will not be refunded or returned, except in our sole discretion. CompStak may also issue Points at no charge to users, at its discretion.</p></li>
                <li><p><span className="underlined">Loss of Points</span>. CompStak may subtract Points from your account if it determines, in its sole discretion, that you did not properly “earn” the Points, including if CompStak Data you previously submitted is outdated or has been superseded by other CompStak Data submission.</p></li>
                <li><p><span className="underlined">Allocation between Members</span>. Points may be transferred among Members who are using the Services under the same Plan (as defined below).</p></li>
              </ol>
            </li>
          </ol>
          <h3>6. Subscription Accounts</h3>
          <ol className="abc">
            <li><p><span className="underlined">Generally</span>. CompStak offers additional, paid, services (each, a "Plan"). Subscription fees and terms vary and additional conditions, restrictions and limitations may apply to each Plan and will be as set forth in a separate agreement between you and CompStak (a “<b>Master Subscription Agreement</b>”).</p></li>
            <li><p><span className="underlined">Method of Payment</span>. Payment terms will be as set forth in the Master Subscription Agreement.</p></li>
          </ol>
          <h3>7. Your License to Use</h3>
          <p>Subject to your compliance with the terms and conditions of this Agreement, and any other agreement between you and CompStak, CompStak grants you a non-exclusive, non-sublicensable, non-assignable, revocable, non-transferable license to access the Services. Except as expressly set forth herein, this Agreement grants you no rights in or to the intellectual property of CompStak or any other party. In the event that you breach any provision of this Agreement, your rights under this paragraph will immediately terminate. By accepting this license, you agree that all information contained in the Database, and the compilation of such information, is the proprietary, confidential information of CompStak, that you will safeguard and protect such information, and that you will use the information in accordance with the Code (as defined below). Your obligations set forth above shall survive termination of this Agreement.</p>
          <h3>8. Code of Conduct</h3>
          <p>The Services allow commercial real estate professionals to share “comp” information. This sharing of information through the functionality of the Services is the only permitted use of the Services. All Members and Visitors must fully comply with the following CompStak Code of Conduct (the “<b>Code</b>”) at all times. You certify, represent and warrant that you will not violate this Code.</p>
          <ol className="abc">
            <li><p><span className="underlined">Restrictions on Inputting Information</span> You shall not enter trade secrets or illegal or improper information in or through the Services (either directly through the Services or via any transmission to CompStak, including email), including, without limitation, the following:</p>
              <ol className="roman">
                <li><p>Information that is known to be false, inaccurate, incorrect, incomplete, inexact, outdated or otherwise wrong;</p></li>
                <li><p>Information subject to confidentiality, non-disclosure, non-competition, trade secret or proprietary rights, limitations or restrictions;</p></li>
                <li><p>Information that infringes the copyrights or intellectual property rights of others;</p></li>
                <li><p>Home addresses, Social Security numbers or credit card numbers;</p></li>
                <li><p>Information that is sexually explicit, profane, pornographic, immoral, obscene, vulgar, offensive, inflammatory, violent, dangerous, harmful, threatening, abusive, harassing, hateful, discriminatory or racially, ethnically or otherwise objectionable, or which may solicit information from anyone under the age of 18;</p></li>
                <li><p>Information that is defamatory, libelous, fraudulent, knowingly incorrect, or invasive of privacy or publicity rights of others;</p></li>
                <li><p>Information that advocates or encourages conduct that could constitute a criminal offense;</p></li>
                <li><p>Information that is actionable or may subject CompStak to legal action or liability of any kind;</p></li>
                <li><p>Information obtained directly from CoStar Group, or any affiliate, subsidiary or related entity of CoStar Realty Information, Inc.</p></li>
                <li><p>Information that violates any applicable local, state, national or international law, regulation, or convention; or</p></li>
                <li><p>Information that violates any provision of this Agreement or any other agreement or policy set forth by CompStak.</p></li>
              </ol>
            </li>
            <li><p><span className="underlined">Use of Information Obtained via the Services</span>. CompStak has no actual control over use of information by you or any other user outside the Services. You shall not use information accessed through the Services for any purpose or in any manner that is illegal or improper, including, without limitation, the following:</p>
              <ol className="roman">
                <li><p>For any purpose, activity or in any manner that is criminal, illegal or actionable;</p></li>
                <li><p>In violation of any local, state, national or international laws, regulations or conventions;</p></li>
                <li><p>To illegally ‘spam’ anyone or to sell, give, make available or otherwise distribute information to a spammer or for the purpose of spamming;</p></li>
                <li><p>For unethical marketing activities;</p></li>
                <li><p>To communicate with anyone using language or in any manner that is sexually explicit, profane, pornographic, immoral, obscene, vulgar, offensive, violent, dangerous, harmful, threatening, abusive, harassing, hateful, discriminatory, or racially, ethnically or otherwise objectionable;</p></li>
                <li><p>To prepare or compile information that is distributed in any manner or form to any third-party;</p></li>
                <li><p>To enhance, verify, supplement, append, confirm, or modify any compilation of information that is thereinafter distributed in any manner or form to a third-party;</p></li>
                <li><p>For sale, re-sale, sub-license, commercial use, or redistribution of any kind, without CompStak’s express, prior consent.;</p></li>
                <li><p>For, at the direction of, or on behalf of (directly or indirectly) any company whose primary business to provide an online commercial real estate analytics platform, including but not limited to, CoStar Group (a “<b>CompStak Competitor</b>”), or to build a competitive product.</p></li>
              </ol>
            </li>
            <li><p><span className="underlined">Acts against the Services</span>. You shall not attempt to or engage in potentially harmful acts that are directed against the Services including, without limitation, the following:</p>
              <ol className="roman">
                <li><p>Using the Services in contravention of any other agreement to which you are a party, including without limitation any employment agreement to which you may be a party;</p></li>
                <li><p>Causing, allowing or assisting any other person to use your account or impersonate you;</p></li>
                <li><p>Sharing your password or login with any other person;</p></li>
                <li><p>Logging onto a server or account that you are not authorized to access;</p></li>
                <li><p>Forging screen names, manipulating identifiers, or otherwise impersonating any other person or misrepresenting your identity or affiliation with any person or entity;</p></li>
                <li><p>Emulating or faking usage of the Services;</p></li>
                <li><p>Violating or attempting to violate any security features of the Services;</p></li>
                <li><p>Using manual or automated software, devices, scripts robots, other means or processes to access, “scrape,” “crawl” or “spider” any pages contained in the Services;</p></li>
                <li><p>Falsely stating or otherwise misrepresenting your affiliation with any person or entity;</p></li>
                <li><p>Introducing viruses, worms, software, Trojan horses or other similar harmful code into the Services;</p></li>
                <li><p>Interfering or attempting to interfere with the use of the Services by any other user, host or network, including, without limitation by means of submitting a virus, overloading, “flooding,” “spamming,” “mail bombing,” or “crashing” the Services;</p></li>
                <li><p>Causing, allowing or assisting machines, bots or automated services to access or use the Services without the express written permission of CompStak;</p></li>
                <li><p>Tampering with the operation, functionality or the security of the Services;</p></li>
                <li><p>Attempting to override or circumvent any security or usage rules embedded into the Services that permit digital materials to be protected;</p></li>
                <li><p>Attempting to probe, scan, or test the vulnerability of the Services, or any associated system or network, or breach any security or authentication measures;</p></li>
                <li><p>Misusing, tricking, disrupting or otherwise interfering with the functioning of the Services;</p></li>
                <li><p>Harvesting or collecting email addresses or other contact information of other users from the Services by electronic or other means;</p></li>
                <li><p>Reverse engineering, decompiling, disassembling, deciphering or otherwise attempting to derive the source code for any underlying intellectual property used to provide the Services;</p></li>
                <li><p>Engaging in “framing,” “mirroring,” or otherwise simulating the appearance or function of the Services;</p></li>
                <li><p>Uploading, posting, transmitting, sharing, storing or otherwise making available any content that CompStak in its sole discretion deems to be harmful, threatening, unlawful, defamatory, infringing, abusive, inflammatory, harassing, vulgar, obscene, fraudulent, invasive of privacy or publicity rights, hateful, or racially, ethnically or otherwise objectionable;</p></li>
                <li><p>Without CompStak’s prior, express consent, advertising or selling any products, services or otherwise (whether or not for profit), or soliciting others or using the Services for commercial purposes of any kind other than sharing comparables information with other real estate professionals.</p></li>
              </ol>
            </li>
            <li><p><span className="underlined">Suspected Misuse and Penalties</span>. CompStak may monitor the Services for violations of the Code, and you agree (a) not to bypass said monitoring, (b) that CompStak will not be liable for monitoring and (c) nothing CompStak says or does waives its rights to monitor the Services. CompStak shall be the sole and final arbiter of suspected Code violations. If CompStak determines that you have materially breached this agreement, it may, and without limiting any of its other remedies, immediately and without notice:</p>
              <ol className="roman">
                <li><p>Delete or modify content;</p></li>
                <li><p>Suspend your account;</p></li>
                <li><p>Terminate your account;</p></li>
                <li><p>Identify you to third parties;</p></li>
                <li><p>Take legal action.</p></li>
              </ol>
            </li>
          </ol>
          <p>You agree that you will be liable for breaches of the Code, and these TOU, by you and your affiliates, consultants, agents, contractors or employees and anyone else accessing the Services on your behalf (directly or indirectly), and you agree to pay CompStak liquidated damages as described below for any such breach of the Code, or these TOU. You agree that damages to CompStak from a breach of the Code or these TOU would be extremely difficult to quantify. Therefore, at CompStak’s option, in lieu of actual damages, CompStack will be entitled to $75,000 in liquidated damages as a reasonable estimate of our damages for each such breach. CompStak intends to cooperate fully with any law enforcement officials or agencies in the investigation of any violation of this Agreement or of any applicable laws.</p>
          <h3>9. Your Creative Content</h3>
          <p>Separate and apart from contributing to the Database, the Services may allow you to post content, such as messages, images, text, photos, graphics, audio, video or other material (<b>“your Creative Content</b>”) through message boards, forums, Member blogs or other interactive features. With respect to your Creative Content, while you retain any and all of your lawfully owned rights therein, you hereby grant CompStak a royalty-free, perpetual, irrevocable, worldwide, transferable, non-exclusive and fully-sublicensable right and license to view, store, reproduce, modify, adapt, publish, translate, create derivative works from, distribute, perform and display your Creative Content (in whole or part) and/or to incorporate it in other works in any form, media, or technology now known or later developed, and to exercise the same rights with respect to such works. You also permit any Visitor of the Services to access, store, distribute, perform, reproduce and prepare derivative works of your Creative Content. No compensation will be paid to you or to any other person or entity with respect to your Creative Content. You grant CompStak the right to use your name and/or likeness and/or any name and/or likeness that you may submit in connection with your Creative Content if CompStak should choose, without compensation or need for your prior approval, or to exercise any of the rights licensed by you hereunder, in connection with a fictional name or persona or without any attribution at all. You also agree to irrevocably waive (and cause to be waived) any claims and assertions of moral rights or attribution with respect to your Creative Content.</p>
          <p>CompStak may remove your Creative Content at any time in its sole discretion. You are solely responsible at your own cost and expense to create backup copies of your Creative Content. Likewise, by accessing the Services you may be exposed to other Members’ Creative Content that you find offensive, indecent or objectionable -- you agree that you use the Services at your own risk.</p>
          <p>You agree that CompStak is not under any obligation of confidentiality, express or implied, with respect to your Creative Content. You represent and warrant that you own or otherwise control all necessary rights to your Creative Content, that it does not violate or infringe upon the intellectual property rights of a third party, that it is accurate, that it does not contain libelous, defamatory or otherwise unlawful material, that it does not violate anyone’s rights to publicity or privacy, that it will not cause injury to any person or entity, that it does not otherwise violate these TOU, and that you will indemnify CompStak and its service providers for all claims resulting from your Creative Content. UNDER NO CIRCUMSTANCES WILL COMPSTAK BE LIABLE IN ANY WAY FOR OR IN CONNECTION WITH YOUR CREATIVE CONTENT.</p>
          <p>As the provider of the Services, CompStak is only a forum and is not liable for any statements, representations, or omissions made through Your (or other Visitors’) Creative Content. Any opinions, advice, purported facts, or recommendations expressed therein are those of the Visitors who make them, and not those of CompStak; CompStak does not endorse any opinion, purported fact, recommendation or advice expressed therein. Likewise, it is your responsibility to exercise due care and caution (for your privacy, safety, and identity, among other concerns) when posting your Creative Content or accessing the Services.</p>
          <h3>10. The Commercial Real Estate Data and Information Available On the Servies</h3>
          <ol className="abc">
            <li><p><span className="underlined">Statement of Principles</span></p>
              <ol className="roman">
                <li><p></p></li>
              </ol>
            </li>
            <li><p><span className="underlined">Statement of Principles</span>.</p>
              <ol className="roman">
                <li><p>We are open, transparent and fair about our practices and policies with respect to the collection and use of information.</p></li>
                <li><p>We utilize our Members and leading edge technology to build and maintain the most comprehensive, accurate and up-to-date database possible of information regarding commercial properties, including building information, completed lease deal information (such as rental rates, leased square footage, tenant names, real estate broker names and salesperson names), and related property, tenant and market information (collectively, “<b>CompStak Data</b>”). We maintain security measures to reasonably safeguard the data and its use.</p></li>
                <li><p>We collect information that is necessary for the legitimate business purposes of CompStak and our Members. We collect information that is obtained lawfully and by fair means, and do not encourage members and users to disclose trade secrets.</p></li>
                <li><p>We will monitor privacy and data protection developments. We encourage Members to respect compliance programs with respect to their own use of the Services.</p></li>
              </ol>
            </li>
            <li><p><span className="underlined">Information Collected</span>. The Services make the following subsets of CompStak Data about commercial properties available to our Members: lease deal information (which may include, but is not limited to, rental rates, leased square footage, lease terms, floor(s) leased, landlord concessions, tenant names, real estate broker name, salesperson name, etc.), and related building information (which may include, but is not limited to, landlord name, address, building name, building agent, year built, building class, etc.).</p>
            </li>
            <li><p><span className="underlined">Sources of CompStak Data</span>.</p>
              <ol className="roman">
                <li><p>Our Members build and maintain the Services’ database of CompStak Data. CompStak may aggregate, supplement or enhance its CompStak Data from established, reputable sources and trusted data suppliers. CompStak may also add to CompStak Data by collecting and including openly and freely available commercial property information. Data providers may only contribute information to CompStak that they have a legal right to provide.</p></li>
                <li><p>CompStak Data available on the Services may be readily available without restriction from any number of different data sources, including:</p>
                  <ol>
                    <li><p>Public records: Records created and maintained by government agencies and open for public inspection and use.</p></li>
                    <li><p>Publicly available information: Information that is available to the general public from non-governmental sources.</p></li>
                    <li><p>Non-public available information provided to CompStak by a Member authorized to share such information: Information that is privately owned and is not available to the general public or that is generally offered for a fee for use and redistribution without restriction.</p></li>
                    <li><p>Openly available information: Information that has been made available without restriction by a property’s representatives, typically for their own convenience, competitive advantage, business benefit or other commercial purposes.</p></li>
                    <li><p>Derived information: Partial or derived information from any combination of the above sources that is assembled, aggregated, appended, calculated or associated together.</p></li>
                  </ol>
                </li>
              </ol>
            </li>
            <li><p><span className="underlined">Concerns about CompStak Data</span>. If you have any concerns about any CompStak Data, you can contact CompStak by email at support@CompStak.com.</p></li>
            <li><p><span className="underlined">Online Privacy Policy (Applicable to Members and Visitors)</span>. The Privacy Policy applies to information collected online from and about our members, users and visitors to CompStak. For more information, see the <a href="#PrivacyPolicy">Privacy Policy</a>.</p></li>
          </ol>
          <h3>11. Intellectual Property</h3>
          <p>The Services and all content and materials located thereon, including without limitation any CompStak names and logos (the “<b>CompStak Marks</b>”), Database, designs, text, graphics and other files, and the selection, arrangement and organization thereof, are the intellectual property of CompStak or its licensors. Except as explicitly provided, neither the Services nor this Agreement grant you any right, title or interest in or to any such content or materials. The CompStak Marks are trademarks or registered trademarks of CompStak. Other trademarks, service marks, graphics, logos and domain names appearing on the Services may be the trademarks of third parties. The Website is Copyright © 2014, CompStak, Inc., ALL RIGHTS RESERVED. Moreover, except as expressly stated herein, or as expressly granted by CompStak in a signed writing, you have no intellectual property or other rights in the information you contribute to the Database.</p>
          <p>As CompStak asks others to respect its intellectual property rights, CompStak respects the intellectual property rights of others. You agree that you shall not remove, obscure, or alter any proprietary rights notices (including copyright and trademark notices) which may be affixed to or contained within the Services. Likewise, if you have evidence, know, or have a good faith belief that your rights have been violated and you want CompStak to delete, edit, or disable the material in question, you must provide CompStak with all of the following information pursuant to the Digital Millennium Copyright Act (“DMCA”) by providing CompStak’s DMCA Agent (listed below) with the following information in writing:</p>
          <ol className="abc">
            <li><p>a physical or electronic signature of a person authorized to act on behalf of the owner of the exclusive right that is allegedly infringed;</p></li>
            <li><p>identification of the copyrighted work claimed to have been infringed, or, if multiple copyrighted works are covered by a single notification, a representative list of such works;</p></li>
            <li><p>identification of the material that is claimed to be infringed or to be the subject of infringing activity and that is to be removed or access to which is to be disabled, and information reasonably sufficient to permit CompStak to locate the material;</p></li>
            <li><p>information reasonably sufficient to permit CompStak to contact you, such as an address, telephone number, and if available, an electronic mail address at which you may be contacted;</p></li>
            <li><p>a statement that you have a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent, or the law; and</p></li>
            <li><p>a statement that the information in the notification is accurate, and under penalty of perjury, that you are authorized to act on behalf of the owner of an exclusive right that is allegedly infringed. For this notification to be effective, you must provide it to CompStak’s designated agent at:</p></li>
          </ol>
          <p>DMCA Agent<br/>
            CompStak.com<br/>
            CompStak, Inc.<br/>
            36 Cooper Square, 6th Floor<br/>
            New York, NY 10003<br/>
            copyright@compstak.com
          </p>
          <p>Please consult your legal counsel (or see 17 U.S.C. § 512) to confirm these requirements and your compliance therewith. It is CompStak’s policy to respond to notices of alleged infringement that comply with the DMCA. In addition, CompStak will promptly terminate without notice the accounts of users that are determined by CompStak to be “repeat infringers.” If CompStak receives more than three takedown notices regarding your any content you have submitted, including your Creative Content, then you will be considered a repeat infringer and your account will be terminated.</p>
          <p>You acknowledge that if you fail to comply with all of the requirements of this section, your DMCA notice may not be valid. Please note that under Section 512(f) of the DMCA, any person who knowingly materially misrepresents that material or activity is infringing may be subject to liability.</p>
          <h3>12. Disclaimers; Limitation of Liability; Third Party Disputes</h3>
          <ol className="abc">
            <li><p><span className="underlined">NO WARRANTIES</span>. ALTHOUGH COMPSTAK TAKES REASONABLE MEASURES TO KEEP THE SERVICES ERROR-FREE AND SAFE, YOU ACCESS THEM AT YOUR OWN RISK. COMPSTAK, ON BEHALF OF ITSELF AND ITS LICENSORS AND SUPPLIERS, HEREBY DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, RELATING TO THE SERVICES, INCLUDING WITHOUT LIMITATION ANY IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NON-INFRINGEMENT. THE SERVICES ARE PROVIDED “AS IS” AND “AS AVAILABLE.” NEITHER COMPSTAK NOR ITS LICENSORS OR SUPPLIERS WARRANT THAT THE SERVICES WILL MEET YOUR REQUIREMENTS OR THAT THE OPERATION OF THE SERVICES WILL BE UNINTERRUPTED, ERROR-FREE, SAFE OR SECURE. COMPSTAK DOES NOT WARRANT AGAINST INTERFERENCE WITH YOUR ENJOYMENT OF THE SERVICE, THAT THE FUNCTIONS CONTAINED IN OR SERVICES PERFORMED OR PROVIDED BY THE SERVICES WILL MEET YOUR REQUIREMENTS, THAT THE OPERATION OF THE SERVICES WILL BE UNINTERRUPTED OR ERROR-FREE OR NOT INTERFERE WITH YOUR USE OR ENJOYMENT OF ANY OTHER PRODUCTS, GOODS OR SERVICES, INCLUDING APPLICATIONS ON ANY MOBILE DEVICE ON WHICH YOU HAVE INSTALLED THE APP, OR THAT DEFECTS IN THE SERVICES WILL BE CORRECTED. NO ORAL OR WRITTEN INFORMATION OR ADVICE GIVEN BY COMPSTAK OR ITS AUTHORIZED REPRESENTATIVES SHALL CREATE A WARRANTY NOT EXPRESSLY PROVIDED FOR IN THE TOU.</p></li>
            <li><p><span className="underlined">YOUR RESPONSIBILITY FOR DAMAGE</span>. YOU AGREE THAT YOUR USE OF THE SERVICES IS AT YOUR SOLE RISK. YOU WILL NOT HOLD COMPSTAK OR ITS LICENSORS OR SUPPLIERS, AS APPLICABLE, RESPONSIBLE FOR ANY DAMAGE OR LOSS THAT RESULTS FROM YOUR USE OF THE SERVICES, INCLUDING WITHOUT LIMITATION ANY DAMAGE TO ANY OF YOUR COMPUTERS OR DATA. THE SERVICES MAY CONTAIN BUGS, ERRORS, PROBLEMS OR OTHER LIMITATIONS.</p></li>
            <li><p><span className="underlined">YOUR RESPONSIBILITY FOR YOUR ACTIONS</span>. YOU AGREE AND UNDERSTAND THAT YOU MAY BE HELD LEGALLY RESPONSIBLE FOR DAMAGES SUFFERED BY OTHER VISITORS OR THIRD PARTIES AS THE RESULT OF YOUR REMARKS, INFORMATION, OR FEEDBACK OR OTHER CONTENT POSTED OR MADE AVAILABLE ON OR THROUGH THE SERVICES THAT IS DEEMED DEFAMATORY OR OTHERWISE LEGALLY ACTIONABLE.</p></li>
            <li><p><span className="underlined">LIMITATION OF LIABILITY</span>. YOU AGREE THAT NEITHER COMPSTAK, ITS DIRECTORS, OFFICERS, EMPLOYEES AND AGENTS, NOR ITS LICENSORS OR SUPPLIERS, HAVE ANY LIABILITY WHATSOEVER IN CONNECTION WITH YOUR ACCESS OF THE SERVICES. COMPSTAK IS NOT RESPONSIBLE FOR THE ACTIONS OF THIRD-PARTIES (INCLUDING OTHER VISITORS OR MEMBERS), AND YOU RELEASE COMPSTAK AND ITS DIRECTORS, OFFICERS, EMPLOYEES AND AGENTS FROM ANY CLAIMS AND DAMAGES, KNOWN OR UNKNOWN, ARISING OUT OF OR IN ANY WAY CONNECTED WITH ANY CLAIM YOU HAVE AGAINST ANY SUCH THIRD-PARTIES. THE LIABILITY OF COMPSTAK, ITS DIRECTORS, OFFICERS, EMPLOYEES, AND AGENTS, AND ITS LICENSORS AND SUPPLIERS, IS LIMITED TO THE MAXIMUM EXTENT PERMITTED BY LAW. IN NO EVENT SHALL COMPSTAK, ITS DIRECTORS, OFFICERS, EMPLOYEES AND AGENTS, OR ITS LICENSORS OR SUPPLIERS, BE LIABLE FOR ANY SPECIAL, INCIDENTAL, PUNITIVE OR CONSEQUENTIAL DAMAGES (INCLUDING WITHOUT LIMITATION LOST PROFITS, LOST DATA OR CONFIDENTIAL OR OTHER INFORMATION, LOSS OF PRIVACY, FAILURE TO MEET ANY DUTY, INCLUDING WITHOUT LIMITATION OF GOOD FAITH OR OF REASONABLE CARE, NEGLIGENCE, OR OTHERWISE, REGARDLESS OF THE FORESEEABILITY OF THOSE DAMAGES OR OF ANY ADVICE OR NOTICE GIVEN TO COMPSTAK, ITS DIRECTORS, OFFICERS, EMPLOYEES, AND AGENTS, OR ITS LICENSORS AND SUPPLIERS) ARISING OUT OF OR RELATING TO YOUR USE OF THE SERVICES. THIS LIMITATION SHALL APPLY REGARDLESS OF WHETHER THE DAMAGES ARISE OUT OF BREACH OF CONTRACT, TORT, OR ANY OTHER LEGAL THEORY OR FORM OF ACTION. ADDITIONALLY, THE MAXIMUM LIABILITY OF COMPSTAK AND ITS DIRECTORS, OFFICERS, EMPLOYEES, AGENTS, LICENSORS AND SUPPLIERS TO YOU UNDER ALL CIRCUMSTANCES WILL NOT EXCEED THE GREATER OF $200.00 USD OR THE AMOUNT YOU HAVE PAID US IN THE LAST 12 MONTHS.</p></li>
            <li><p><span className="underlined">APPLICATION</span>. THE ABOVE DISCLAIMERS, WAIVERS AND LIMITATIONS DO NOT IN ANY WAY LIMIT ANY OTHER DISCLAIMER OF WARRANTIES OR ANY OTHER LIMITATIONS OF LIABILITY BETWEEN YOU AND COMPSTAK OR BETWEEN YOU AND ANY OF COMPSTAK’S DIRECTORS, OFFICERS, EMPLOYEES, AGENTS, LICENSORS OR SUPPLIERS. SOME JURISDICTIONS MAY NOT ALLOW THE EXCLUSION OF CERTAIN IMPLIED WARRANTIES OR THE LIMITATION OF CERTAIN DAMAGES, SO SOME OF THE ABOVE DISCLAIMERS, WAIVERS AND LIMITATIONS OF LIABILITY MAY NOT APPLY TO YOU. UNLESS LIMITED OR MODIFIED BY APPLICABLE LAW, THE FOREGOING DISCLAIMERS, WAIVERS AND LIMITATIONS SHALL APPLY TO THE MAXIMUM EXTENT PERMITTED, EVEN IF ANY REMEDY FAILS ITS ESSENTIAL PURPOSE. NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY YOU THROUGH THE WEBSITE, SERVICES, OR OTHERWISE SHALL ALTER ANY OF THE DISCLAIMERS OR LIMITATIONS STATED IN THIS SECTION.</p></li>
            <li><p><span className="underlined">THIRD PARTY DISPUTES</span>. YOU IRREVOCABLY RELEASE COMPSTAK (AND OUR OFFICERS, DIRECTORS, AGENTS, SUBSIDIARIES, JOINT VENTURES, AND EMPLOYEES) FROM ANY AND ALL CLAIMS, DEMANDS AND DAMAGES (ACTUAL AND CONSEQUENTIAL) OF EVERY KIND AND NATURE, KNOWN AND UNKNOWN, ARISING OUT OF OR IN ANY WAY CONNECTED WITH ANY DISPUTE YOU HAVE WITH ANY SERVICE PROVIDER, THIRD PARTY SERVICE OR OTHER THIRD PARTY.</p></li>
          </ol>
          <h3>13. Indemnification</h3>
          <p>You agree to indemnify and hold CompStak, its directors, officers, employees and agents, and its suppliers, licensors, and service providers, harmless from and against any loss, liability, claim, demand, damages, costs and expenses, including reasonable attorneys' fees (collectively, “<b>Claims</b>”), arising out of or in connection with: (1) your use of the Services; (2) any violation of this Agreement (including, without limitation, the Code); and (3) your violation of any law or the rights of any third party. CompStak will have the right, but not the obligation, to participate through counsel of its choice in any defense by you of any Claims as to which you are required to defend, indemnify, or hold harmless CompStak. You may not settle any Claims without the prior written consent of the concerned CompStak person or persons.</p>
          <h3>14. Third Party Websites</h3>
          <p>On the Services, you may find links to websites operated by third parties (“<b>Third-Party Sites</b>”). CompStak does not endorse or control Third-Party Sites, each of which may be governed by its own terms of service and privacy policy. CompStak disclaims, and you hereby agree to assume, all responsibility and liability for any damages or other harm, whether to you or third-parties, resulting from your use of Third-Party Sites and any content found on those Third-Party Sites. Please take all protections necessary to protect yourself and your computer system when accessing Third-Party Sites, particularly when downloading or purchasing anything therefrom. Your correspondence or business dealings with, or participation in promotions of, advertisers found on or through the Services are solely between you and such advertiser. YOU AGREE THAT YOUR USE OF CONTENT FROM THIRD-PARTY SITES IS AT YOUR OWN RISK AND COMPSTAK WILL NOT BE RESPONSIBLE OR LIABLE FOR ANY LOSS OR DAMAGE OF ANY SORT INCURRED AS THE RESULT OF ANY SUCH USE OR DEALINGS, OR AS THE RESULT OF THE PRESENCE OF ADVERTISERS ON THE SERVICES.</p>
          <h3>15. Termination</h3>
          <ol className="abc">
            <li><p><span className="underlined">By You</span>. You may cancel your account at any time and for any reason through the “My Account” link. WHEN YOU TERMINATE YOUR ACCOUNT, YOU WILL NOT RECEIVE ANY REFUND OF ANY SUBSCRIPTION FEES CHARGED TO YOUR ACCOUNT PRIOR TO RECEIPT OF YOUR CANCELLATION. WHERE APPLICABLE, AND UNLESS OTHERWISE SET FORTH IN YOUR SPECIFIC PLAN DETAILS, YOUR ACCOUNT WILL REMAIN ACTIVE UNTIL THE END OF YOUR CURRENT SUBSCRIPTION TERM UNLESS OTHERWISE TERMINATED BY COMPSTAK. SUBSCRIPTION FEES WILL NOT BE PRORATED OR REFUNDED FOR PARTIAL-MONTH USAGE. YOU WILL FORFEIT YOUR ACCUMULATED POINTS AND RATING AT THE END OF THE SUBSCRIPTION TERM AFTER THE EFFECTIVE DATE OF YOUR CANCELLATION.</p></li>
            <li><p><span className="underlined">By CompStak</span>. CompStak may suspend, terminate, or disable access to your account at any time for an actual or suspected breach (in CompStak’s reasonable discretion) of any provision of the TOU. CompStak, in its sole discretion and for any reason or no reason, may discontinue the Services and any related services including support (or any part thereof), at any time, with or without notice. You agree that CompStak shall not be liable to you or any third-party for any such termination. Without limiting the generality of the foregoing, CompStak may terminate your access to the Services in cases of actual or suspected fraud, or violations of these TOU or other laws or regulations, and any suspected fraudulent, abusive, or illegal activity may be referred to appropriate law enforcement authorities. These remedies are in addition to any other remedies CompStak may have at law or in equity. Upon termination, you will no longer have access to the Services and will forfeit your accumulated points and rating . At our discretion, we may provide you with a prorated refund of subscription fees if we terminate your user account.</p></li>
            <li><p><span className="underlined">Effect of Termination; Survival</span><br/>If this Agreement terminates, you will no longer be authorized to access the Services. Sections 8 – 13 and 15 – 18 of the Agreement will survive termination.</p></li>
          </ol>
          <h3>16. Arbitration, Venue and Jurisdiction</h3>
          <ol className="abc">
            <li><p><span className="underlined">Mandatory Arbitration</span>. Please read this carefully. It affects your rights. YOU AND COMPSTAK AND EACH OF OUR RESPECTIVE CORPORATE PARENTS, SUBSIDIARIES, AFFILIATES, PREDECESSORS IN INTEREST, SUCCESSORS, AND PERMITTED ASSIGNS AGREE TO ARBITRATION (EXCEPT FOR MATTERS THAT MAY BE TAKEN TO SMALL CLAIMS COURT), AS THE EXCLUSIVE FORM OF DISPUTE RESOLUTION EXCEPT AS PROVIDED FOR BELOW, FOR ALL DISPUTES AND CLAIMS ARISING OUT OF OR RELATING TO THESE TERMS OR YOUR USE OF THE SERVICE. Arbitration is more informal than a lawsuit in court. Arbitration uses a neutral arbitrator instead of a judge or jury, allows for more limited discovery than in court, and is subject to very limited review by courts. Arbitrators can award the same damages and relief that a court can award. Please visit www.adr.org for more information about arbitration.</p>
              <ol className="roman">
                <li><p><span className="underlined">Commencing Arbitration</span>. A party who intends to seek arbitration must first send to the other, by certified mail, a written notice of intent to arbitrate (a “Notice”), or, in the absence of a mailing address provided by you to CompStak, to you via any other method available to CompStak, including via e-mail. The Notice to CompStak should be addressed to CompStak, Inc., 36 Cooper Square, Suite 4F, New York, NY 10003, Attn: Chief Operating Officer (the “<b>Arbitration Notice Address</b>”). The Notice must (A) describe the nature and basis of the claim or dispute; and (B) set forth the specific relief sought (the “<b>Demand</b>”). If you and CompStak do not reach an agreement to resolve the claim within thirty (30) days after the Notice is received, then you or CompStak may commence an arbitration proceeding as set forth below or file a claim in small claims court. THE ARBITRATION SHALL BE ADMINISTERED BY THE AMERICAN ARBITRATION ASSOCIATION (“<b>AAA</b>”) IN ACCORDANCE WITH ITS COMMERCIAL ARBITRATION RULES AND THE SUPPLEMENTARY PROCEDURES FOR CONSUMER RELATED DISPUTES (THE “<b>Rules</b>”), AS MODIFIED BY THIS AGREEMENT. The Rules and AAA forms are available online at <a target="_blank" href="http://www.adr.org/">www.adr.org</a>. If you are required to pay a filing fee to commence an arbitration against CompStak, then CompStak will promptly reimburse you for your confirmed payment of the filing fee upon CompStak’s receipt of Notice at the Arbitration Notice Address that you have commenced arbitration along with a receipt evidencing payment of the filing fee, unless your Demand is equal to or greater than $1,000 or was filed in bad faith (as determined by the arbitrator), in which case you are solely responsible for the payment of the filing fee.</p></li>
                <li><p><span className="underlined">Arbitration Proceeding</span>. The arbitration will be conducted in the English language. A single independent and impartial arbitrator with his or her primary place of business in New York, New York shall be appointed pursuant to the Rules, as modified herein. You and CompStak agree to comply with the following rules, which are intended to streamline the dispute resolution process and reduce the costs and burdens on the parties: (A) the arbitration will be conducted by telephone, online and/or be solely based on written submissions, the specific manner to be chosen by the party initiating the arbitration; (B) the arbitration will not require any personal appearance by the parties or witnesses unless otherwise mutually agreed in writing by the parties; and (C) any judgment on the award rendered by the arbitrator may be entered in any court of competent jurisdiction.</p></li>
                <li><p><span className="underlined">No Class Actions</span>. YOU AND COMPSTAK AGREE THAT YOU AND COMPSTAK MAY BRING CLAIMS AGAINST THE OTHER ONLY IN YOUR OR ITS INDIVIDUAL CAPACITY AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS OR REPRESENTATIVE PROCEEDING. FURTHER, YOU AGREE THAT THE ARBITRATOR MAY NOT CONSOLIDATE PROCEEDINGS OF MORE THAN ONE PERSON’S CLAIMS, AND MAY NOT OTHERWISE PRESIDE OVER ANY FORM OF A REPRESENTATIVE OR CLASS PROCEEDING, AND THAT IF THIS SPECIFIC PROVISO IS FOUND TO BE UNENFORCEABLE, THEN THE ENTIRETY OF THIS MANDATORY ARBITRATION SECTION SHALL BE NULL AND VOID.</p></li>
                <li><p><span className="underlined">Decision of the Arbitrator</span>. Barring extraordinary circumstances, the arbitrator shall issue his or her decision within 120 days from the date the arbitrator is appointed. The arbitrator may extend this time limit for an additional 30 days in the interests of justice. All arbitration proceedings will be closed to the public and confidential, and all records relating thereto shall be permanently sealed, except as necessary to obtain court confirmation of the arbitration award. The award of the arbitrator shall be in writing and will include a statement setting forth the reasons for the disposition of any claim. The arbitrator will apply the laws of the State of New York in conducting the arbitration. You acknowledge that these terms and your use of the Service evidences a transaction involving interstate commerce. The United States Federal Arbitration Act will govern the interpretation, enforcement, and proceedings pursuant to the Mandatory Arbitration clause in the TOU.</p></li>
              </ol>
            </li>
            <li><p><span className="underlined">Equitable Relief</span>. Should you or CompStak seek equitable relief of any kind, you or CompStak, as applicable, are permitted to seek equitable relief in court, in aid of arbitration.</p></li>
            <li><p><span className="underlined">Claims</span>. You and CompStak agree that, notwithstanding any other rights the party may have under law or equity, any cause of action arising out of or related to the TOU or the Services, excluding a claim for indemnification, must commence within one year after the cause of action accrues. Otherwise, such cause of action is permanently barred.</p></li>
            <li><p><span className="underlined">Improperly Filed Claims</span>. All claims you bring against CompStak, or CompStak brings against you, must be resolved in accordance with this Dispute Resolution section. All claims filed or brought contrary to this Dispute Resolution section will be considered improperly filed. Should you or CompStak (the “ Filing Party”) file a claim contrary to this Dispute Resolution section, the non-Filing Party may recover attorneys’ fees and costs up to $5,000, provided that the non-Filing Party has notified in writing of the improperly filed claim, and the Filing Party has failed to promptly withdraw the claim.</p></li>
            <li><p><span className="underlined">Modifications</span>. In the event that CompStak makes any future change to the Mandatory Arbitration provision (other than a change to CompStak’s Arbitration Notice Address), you may reject any such change by sending us written notice within thirty (30) days of the effective date of the change to CompStak’s Arbitration Notice Address, in which case your account with CompStak and your license to use the Services shall terminate immediately, and this Dispute Resolution provision, as in effect immediately prior to the amendments you reject, shall survive the termination of the TOU.</p></li>
            <li><p><span className="underlined">Enforceability</span>. If only Section 16(a)(iii) or the entirety of this Section 16 is found to be unenforceable, then the entirety of this Section 16 shall be null and void and, in such case, the parties agree that the exclusive jurisdiction and venue described in Section 16.G shall govern any action arising out of or related to the TOU.</p></li>
            <li><p><span className="underlined">Governing Law; Choice of Forum</span>. The laws of the State of New York, excluding its conflicts of law rules, govern the TOU and your use of the Services. Your use of the Services may also be subject to other local, state, national, or international laws; provided, however, that the United Nations Convention on Contracts for the International Sale of Goods shall not apply to any provision of this TOU. To the extent that any action relating to any dispute hereunder is permitted to be brought in a court of law, such action shall be subject to the exclusive jurisdiction of the state and federal courts located in New York, New York, and you hereby irrevocably submit to personal jurisdiction in such courts, and waive any defense of inconvenient forum.</p></li>
            <li><p><span className="underlined">Specific Proceedings</span>. Any legal process initiated in order to obtain identifying information of a Visitor or Member in connection with asserting claims against such user must be initiated by way of a pre-action discovery proceeding in New York state court under N.Y. C.P.L.R. § 3102(c). If you are concerned about whether any Member is sharing information he/she is not authorized to share, please contact us at legal@compstak.com and we will endeavor to work with you to resolve your concerns without the need to commence a legal proceeding.</p></li>
          </ol>
          <h3>17. Feedback</h3>
          <p>CompStak values your enthusiasm regarding the Services. If you choose to contribute by sending CompStak or our employees any ideas for products, services, features, modifications, enhancements, content, refinements, technologies, content offerings (such as audio, visual, games, or other types of content), promotions, strategies, or product/feature names, or any related documentation, artwork, computer code, diagrams, or other materials (collectively “<b>Feedback</b>”), then regardless of what your accompanying communication may say, the following terms shall apply, so that future misunderstandings can be avoided. Accordingly, by sending Feedback to CompStak, you agree that:</p>
          <ol className="abc">
            <li>CompStak has no obligation to review, consider, or implement your Feedback, or to return to you all or part of any Feedback for any reason;</li>
            <li>Feedback is provided on a non-confidential basis, and CompStak is not under any obligation to keep any Feedback you send confidential or to refrain from using or disclosing it in any way; and</li>
            <li>You irrevocably grant CompStak and its successors and assigns perpetual and unlimited permission to reproduce, distribute, create derivative works of, modify, publicly perform (including on a through-to-the-audience basis), communicate to the public, make available, publicly display, and otherwise use and exploit the Feedback and derivatives thereof for any purpose and without restriction, free of charge and without attribution of any kind, including by making, using, selling, offering for sale, importing, and promoting commercial products and services that incorporate or embody Feedback, whether in whole or in part, and whether as provided or as modified.</li>
          </ol>
          <h3>18. Miscellaneous</h3>
          <ol className="abc">
            <li>CompStak’s failure to exercise or enforce any right or provision of this Agreement shall not constitute a waiver of such right or provision.</li>
            <li>If any provision of this Agreement shall be deemed unlawful, void, or for any reason unenforceable, then that provision shall be deemed severable from the Agreement and shall not affect the validity and enforceability of any remaining provisions.</li>
            <li>Neither the course of conduct and/or course of dealing between the parties nor trade practice shall act to modify any provision of this Agreement.</li>
            <li>CompStak may assign its rights and duties under this Agreement to any party at any time without notice to you. Your rights and duties under this Agreement are not assignable by you without written consent of CompStak.</li>
            <li>Headings are used for convenience only and are not to be used for meaning or intent.</li>
            <li>This Agreement, along with your Plan, and any other signed writing between you and CompStak regarding the Services, constitutes the entire understanding between you and CompStak and supersedes any prior or contemporaneous communications or provisions on the subject matter. This Agreement cannot be modified, unless in a writing labeled “Modification to TOU”, executed by both you and an officer of CompStak.</li>
          </ol>
          <p>CompStak, Inc.</p>
          <p>
            Attn: Legal Department<br/>
            36 Cooper Square<br/>
            6th Floor<br/>
            New York, NY, 10003<br/>
            Legal@CompStak.com<br/>
          </p>
        </div>
      </section>
    )
  }
});

module.exports = TermsOfUse;